### ISSUE TITLE
persistent_logins 의 목적을 알려주세요

### ISSUE THREAD

**Issue by misolab** [AyoungLim1103/spring-multi#17]
코드를 보던중 `Persistent_logins`클래스를 봤는데 대충 로그인 정보를 DB에 저장하려것 같았습니다.
어떤 정보를 참고하셨던 건지 공유 부탁드립니다.

내용 참고 후 기존에 제가 사용했던 방법도 같이 말씀드리겠습니다.

**Comment by AyoungLim1103** [comment]
Remeber-Me 를 구현하기 위함입니다.
책의 "8.6.3 remember-me를 데이터베이스에 보관하기" (454p)를 참고하였습니다.
로그인에 사용될 Token 을 저장하기 위한 목적으로 JdbcTokenRepositoryImple을 활용하였습니다.
