### ISSUE TITLE
REVIEW-1

### ISSUE THREAD

**Issue by misolab** [AyoungLim1103/spring-multi#9]
####  security dependency
SITE pom.xml 에 추가하신거 API, ADMIN 모듈에 영향 안 줄려고 그러신거죠? ㅎ

WEB pom.xml에 주석으로 막아 놓은게 있어요
어차피 API, ADMIN 다 적용돼야해서 상위로 올려놓았습니다.

선언이 어디에 있느냐보다 어떻게 구현이 먼저이니 SITE 에서 작업 후 
공통 코드와 같이 상위 모듈(WEB)올리는 작업은 같이 하시죠

#### datasource-XXX.properties
`datasource-arumu.properties`, `datasource-ayoung.properties` 멋지십니다. 잘하셨어요 👍 
개인 설정이니 .gitignore에도 추가해서 저장소에 안 올리는 것도 좋을것 같아요
저도 보안 관련 정보는 따로 빼야하는 방법을 연구해보겠습니다.

---
바쁜중에도 이렇게 열심히 진행해주셔서 감사합니다.
재택으로 소통하기 어려운데 얼굴볼때 있으면 꼭 같이 뵙고 또 말씀나누시죠..
정말 수고 많으셨습니다.

**Comment by a-ri-mu** [comment]
넵넵 감사합니다:)

**Comment by a-ri-mu** [comment]
@misolab  datasource-arumu.properties, datasource-ayoung.properties 2개 .gitignore 추가했습니다:)
